FLAGS = -Wall -pedantic -g -lpthread

1:
	gcc sem-prioridade.c $(FLAGS) -o sem-prioridade

2:
	gcc escrita-prioridade.c $(FLAGS) -o escrita-prioridade

3:
	gcc igual-prioridade.c $(FLAGS) -o igual-prioridade
